
services:
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile.front
    image: matifsarwar/frontend:v4
    container_name: spooky-stories-frontend
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://backend:4000/api
    depends_on:
      - backend
    restart: unless-stopped

  backend:
      build:
        context: ./server
        dockerfile: Dockerfile.backend
      ports:
        - "4000:4000"
      image: matifsarwar/backend:v2
      container_name: spooky-stories-backend
      env_file:
        - ./server/.env
      restart: unless-stopped