
services:
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile.front
    image: matifsarwar/frontend:v2
    container_name: spooky-stories-frontend
    ports:
      - "3000:3000"
    restart: unless-stopped