name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
# frontend test
  test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front-end
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run build
      - run: npm test

# backend test
  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run build
      - run: npm test

# build images and pushing to docker hub
  build-image:
    needs: [test-frontend, test-backend]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
        #building backend frontend image
      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./front-end
          file: ./front-end/Dockerfile.front
          push: true
          build-args: |
            API_URL=${{ secrets.API_URL }}/api
          tags: ${{ secrets.DOCKER_USERNAME }}/frontend:latest
            
        # building backeend images
      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./server
          file: ./server/Dockerfile.backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/backend:latest

  deploy:
    needs: build-image
    runs-on: ubuntu-latest
    steps:
      - name: Deploy fronetend
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_FRONTEND }}"
       
      - name: Trigger Render deploy - backend
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_BACKEND }}"